### ISSUE TITLE
Kolokvij

### ISSUE THREAD

**Issue by tsculac** [josipkrnic/krnicPAF#6]
- 1. zadatak: **12/20** ne ispisuje se odmah kod stvaranja objekta u funkciji __init__()
- 2. zadatak: **5/20** nema metoda za promjenu brzine/visine
- 3. zadatak: **0/20** 
- 4. zadatak: **20/20** 
- 5. zadatak: **0/20**
Ukupno: **37/100**

**Comment by josipkrnic** [comment]
Dobar dan profesore, značl u drugom zadatku ne vrijedi ono laički pitati korisnika želi li promijeniti brzinu nego je bila potrebna baš funkcija za to? I je li se treći zadatak temeljio samo na crtanju grafa ili?
________________________________
From: Toni Sculac ***@***.***>
Sent: Tuesday, April 20, 2021 1:14 PM
To: josipkrnic/krnicPAF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [josipkrnic/krnicPAF] Kolokvij (#6)


  *
     *   zadatak: 12/20 ne ispisuje se odmah kod stvaranja objekta u funkciji init()
  *
     *   zadatak: 5/20 nema metoda za promjenu brzine/visine
  *
     *   zadatak: 0/20
  *
     *   zadatak: 20/20
  *
     *   zadatak: 0/20
Ukupno: 37/100

**Comment by tsculac** [comment]
- U drugom zadatku se trazi da klasa sadrzi metodu uz pomoc koje korisnik moze promjeniti brzinu i visinu i da pokazete njenu primjenu. Npr., p1.change_speed(40) ili p1.change_hight(40)
- U trećem zadatku morate napisati funkciju koja vraca liste potrebne za crtanje v-t i h-t grafova i nacrtati te grafove, a Vi nemate ni jedno pa ste zato dobili 0 bodova
